package com.restproject.mobile.activities;

public enum RequestEnums {
    HOME_GET_ALL_SCHEDULE,
    HOME_GET_SCHEDULE_DETAIL,
    HOME_UPDATE_REP_RATIO,
    AVAILABLE_SCHE_GET_ALL_SCHEDULE,
    AVAILABLE_SCHE_GET_SCHEDULE_DETAIL,
    GET_ALL_AIMS,
    SUBSCRIBE_SCHEDULE,
    PROFILE_GET_USER_INFO,
    PROFILE_UPDATE_USER_INFO,
    CHANGE_PASS_GET_OTP,
    CHANGE_PASS_VERIFY_OTP,
    CHANGE_PASS_CHANGE_PASSWORD,
    DEPOSIT_COINS_GET_URL,
    DEPOSIT_COINS_GET_TRANS_STATUS, COINS_HISTORIES_GET_HISTORIES,
    FAST_API_CAL_BODY,
    FAST_API_GET_SCHEDULE,
    GEN_SCHE_GET_SCHEDULE_DETAIL,
    SUBSCRIBE_SCHEDULE_AI,
    GET_SESSION_DETAIL,

}
