package com.restproject.mobile.activities;

public enum RequestEnums {
    HOME_GET_ALL_SCHEDULE, HOME_GET_SCHEDULE_DETAIL, HOME_UPDATE_REP_RATIO, AVAILABLE_SCHE_GET_ALL_SCHEDULE, AVAILABLE_SCHE_GET_SCHEDULE_DETAIL, GET_ALL_AIMS, SUBSCRIBE_SCHEDULE, PROFILE_GET_USER_INFO, PROFILE_UPDATE_USER_INFO, CHANGE_PASS_GET_OTP, CHANGE_PASS_VERIFY_OTP, CHANGE_PASS_CHANGE_PASSWORD,
}
