package com.restproject.mobile.activities;

public enum RequestEnums {
    HOME_GET_ALL_SCHEDULE, HOME_GET_SCHEDULE_DETAIL, HOME_UPDATE_REP_RATIO, AVAILABLE_SCHE_GET_ALL_SCHEDULE, AVAILABLE_SCHE_GET_SCHEDULE_DETAIL, GET_ALL_AIMS, SUBSCRIBE_SCHEDULE,
}
